import { RuleDefinition } from '../types';

export const CORE_RULES: RuleDefinition[] = [
  {
    id: 'aws-access-key',
    name: 'AWS Access Key ID',
    provider: 'Amazon Web Services',
    pattern: /\b((?:AKIA|ASIA|ABIA|ACCA)[0-9A-Z]{16})\b/g,
    baseConfidence: 98,
    baseRiskWeight: 95,
    signals: [
      'AWS IAM standard 20-character key prefix (AKIA/ASIA/ABIA/ACCA)',
      'Deterministic uppercase alphanumeric structure',
      'Direct cloud resource control & hijacking capability',
    ],
    suggestedEnvName: () => 'AWS_ACCESS_KEY_ID',
    remediationInstructions: [
      'Revoke the exposed Access Key ID immediately in AWS IAM Management Console.',
      'Check AWS CloudTrail logs for unauthorized API calls originated by this key.',
      'Transition to IAM Roles for Amazon EC2 or AWS IAM Identity Center (SSO).',
      'Never store access keys in source code; use AWS_ACCESS_KEY_ID environment variable.',
    ],
  },
  {
    id: 'aws-secret-key',
    name: 'AWS Secret Access Key',
    provider: 'Amazon Web Services',
    pattern: /(?:aws_secret_access_key|aws_secret_key|secret_access_key)\s*[:=]\s*["']([A-Za-z0-9/+=]{40})["']/gi,
    baseConfidence: 94,
    baseRiskWeight: 95,
    minEntropy: 4.1,
    signals: [
      'Contextual AWS credential parameter match',
      'High-entropy 40-character Base64 payload',
      'Pairs with AWS Access Key for root/IAM API authentication',
    ],
    suggestedEnvName: () => 'AWS_SECRET_ACCESS_KEY',
    remediationInstructions: [
      'Rotate the key pair immediately in the AWS IAM Console.',
      'Audit AWS KMS and S3 bucket accesses during exposure window.',
      'Store secrets in AWS Secrets Manager or Parameter Store.',
    ],
  },
  {
    id: 'github-pat',
    name: 'GitHub Personal Access Token',
    provider: 'GitHub',
    pattern: /\b(gh[pousr]_[A-Za-z0-9_]{36,255}|github_pat_[A-Za-z0-9_]{82})\b/g,
    baseConfidence: 99,
    baseRiskWeight: 95,
    signals: [
      'Official GitHub token format prefix (ghp_, gho_, ghu_, ghs_, github_pat_)',
      'Deterministic token structure and length',
      'Permits repository code modification, workflow execution, or release poisoning',
    ],
    suggestedEnvName: () => 'GITHUB_TOKEN',
    remediationInstructions: [
      'Revoke token immediately at https://github.com/settings/tokens.',
      'Check GitHub Security Audit Log for unauthorized repository clones or writes.',
      'Use GitHub fine-grained PATs with scoped repository permissions.',
      'Use GitHub Actions secrets rather than personal tokens for CI/CD.',
    ],
  },
  {
    id: 'google-api-key',
    name: 'Google Cloud / Gemini API Key',
    provider: 'Google Cloud',
    pattern: /\b(AIza[0-9A-Za-z_-]{34,35})\b/g,
    baseConfidence: 96,
    baseRiskWeight: 90,
    minEntropy: 3.5,
    signals: [
      'Google standard AIza service key signature',
      'Fixed 39-character alphanumeric structure',
      'Access to Google Cloud Platform APIs and billing services',
    ],
    suggestedEnvName: () => 'GEMINI_API_KEY',
    remediationInstructions: [
      'Restrict or delete the API key in Google Cloud Console Credentials page.',
      'Apply API restrictions (e.g. restrict solely to Generative Language API).',
      'Apply HTTP referrer or IP address restrictions.',
      'Store in GEMINI_API_KEY environment variable.',
    ],
  },
  {
    id: 'openai-api-key',
    name: 'OpenAI API Key',
    provider: 'OpenAI',
    pattern: /\b(sk-proj-[A-Za-z0-9_-]{48,}|sk-[A-Za-z0-9]{32,48})\b/g,
    baseConfidence: 97,
    baseRiskWeight: 92,
    minEntropy: 4.0,
    signals: [
      'OpenAI official secret prefix (sk-proj- or sk-)',
      'High Shannon entropy key payload',
      'Direct account credit exhaustion and model theft risk',
    ],
    suggestedEnvName: () => 'OPENAI_API_KEY',
    remediationInstructions: [
      'Revoke key at https://platform.openai.com/api-keys.',
      'Verify credit consumption in OpenAI usage dashboard.',
      'Inject credentials using OPENAI_API_KEY environment variable.',
    ],
  },
  {
    id: 'anthropic-api-key',
    name: 'Anthropic Claude API Key',
    provider: 'Anthropic',
    pattern: /\b(sk-ant-[A-Za-z0-9_-]{40,})\b/g,
    baseConfidence: 98,
    baseRiskWeight: 92,
    minEntropy: 3.8,
    signals: [
      'Anthropic official secret token signature (sk-ant-)',
      'High entropy cryptographic token payload',
      'Direct Claude model API billing access',
    ],
    suggestedEnvName: () => 'ANTHROPIC_API_KEY',
    remediationInstructions: [
      'Revoke the API key in Anthropic Console.',
      'Generate replacement key with spend limit configured.',
      'Inject via ANTHROPIC_API_KEY environment variable.',
    ],
  },
  {
    id: 'stripe-secret-key',
    name: 'Stripe Secret Key',
    provider: 'Stripe',
    pattern: /\b((?:sk|rk)_(?:live|test)_[0-9a-zA-Z]{24,34})\b/g,
    baseConfidence: 97,
    baseRiskWeight: 96,
    signals: [
      'Stripe signature prefix (sk_live / rk_live / sk_test)',
      'Financial transaction and customer credit card access',
      'High financial liability and compliance breach',
    ],
    suggestedEnvName: () => 'STRIPE_SECRET_KEY',
    remediationInstructions: [
      'Roll API key immediately in Stripe Dashboard > Developers > API keys.',
      'Audit recent transactions and payout bank account modifications.',
      'Never bundle Stripe secret keys in frontend or mobile client builds.',
    ],
  },
  {
    id: 'slack-bot-token',
    name: 'Slack OAuth / Bot Token',
    provider: 'Slack',
    pattern: /\b(xox[baprs]-[0-9A-Za-z-]{10,72})\b/g,
    baseConfidence: 95,
    baseRiskWeight: 82,
    signals: [
      'Slack OAuth bot/user prefix (xoxb/xoxp/xoxa)',
      'Internal company communications and workspace access',
    ],
    suggestedEnvName: () => 'SLACK_BOT_TOKEN',
    remediationInstructions: [
      'Revoke token in api.slack.com/apps.',
      'Re-install app with minimal necessary OAuth scopes.',
    ],
  },
  {
    id: 'slack-webhook',
    name: 'Slack Incoming Webhook URL',
    provider: 'Slack',
    pattern: /(https:\/\/hooks\.slack\.com\/services\/T[A-Z0-9_]{8,12}\/B[A-Z0-9_]{8,12}\/[A-Za-z0-9_]{24})/g,
    baseConfidence: 98,
    baseRiskWeight: 78,
    signals: [
      'Slack Incoming Webhook URL structure',
      'Enables unauthorized message spoofing and channel phishing',
    ],
    suggestedEnvName: () => 'SLACK_WEBHOOK_URL',
    remediationInstructions: [
      'Delete the exposed webhook URL in Slack App settings.',
      'Generate a new webhook URL and store in SLACK_WEBHOOK_URL.',
    ],
  },
  {
    id: 'azure-storage-key',
    name: 'Azure Shared Storage Key',
    provider: 'Microsoft Azure',
    pattern: /(?:AccountKey|azure_secret|azure_key)\s*[:=]\s*["']([A-Za-z0-9/+=]{86,88}==)["']/gi,
    baseConfidence: 93,
    baseRiskWeight: 90,
    minEntropy: 4.2,
    signals: [
      'Azure storage account key signature (86-88 chars base64 with == padding)',
      'Full administrative access to Azure Blob/Queue/Table storage',
    ],
    suggestedEnvName: () => 'AZURE_STORAGE_KEY',
    remediationInstructions: [
      'Regenerate storage key in Azure Portal.',
      'Adopt Azure Managed Identity or Microsoft Entra ID authentication instead.',
    ],
  },
  {
    id: 'private-key',
    name: 'Cryptographic Private Key (PEM)',
    provider: 'Cryptography',
    pattern: /(-----BEGIN (?:RSA|EC|DSA|OPENSSH|PGP) PRIVATE KEY-----[\s\S]*?-----END (?:RSA|EC|DSA|OPENSSH|PGP) PRIVATE KEY-----)/g,
    baseConfidence: 100,
    baseRiskWeight: 100,
    signals: [
      'Standard PEM container header and footer',
      'Unencrypted cryptographic private key',
      'Total server impersonation, SSH compromise, or TLS decryption risk',
    ],
    suggestedEnvName: () => 'PRIVATE_KEY_PATH',
    remediationInstructions: [
      'Immediately decommission this private key pair.',
      'Remove public key counterpart from all servers authorized_keys.',
      'Never commit private keys to version control; use SSH agents or secret vaults.',
    ],
  },
  {
    id: 'database-url',
    name: 'Database Connection String with Credentials',
    provider: 'Database',
    pattern: /\b((?:postgres|postgresql|mysql|mongodb(?:\+srv)?|redis):\/\/[^:\s'"]+:([^@\s'"]+)@[a-zA-Z0-9.-]+(?::[0-9]+)?\/[^\s'"]+)/gi,
    baseConfidence: 92,
    baseRiskWeight: 88,
    minEntropy: 3.2,
    signals: [
      'Database connection URL containing embedded user:password credentials',
      'Direct data exfiltration, deletion, or ransomware risk',
    ],
    suggestedEnvName: () => 'DATABASE_URL',
    remediationInstructions: [
      'Rotate the database user password immediately on the database server.',
      'Migrate connection string to DATABASE_URL environment variable.',
      'Enable SSL/TLS requirement and VPC network access controls.',
    ],
  },
  {
    id: 'jwt-token',
    name: 'JSON Web Token (JWT)',
    provider: 'Auth / Identity',
    pattern: /\b(ey[A-Za-z0-9_-]{15,}\.ey[A-Za-z0-9_-]{15,}\.[A-Za-z0-9_-]{10,})\b/g,
    baseConfidence: 88,
    baseRiskWeight: 75,
    minEntropy: 4.1,
    signals: [
      'Header.Payload.Signature Base64 tripartite JWT structure',
      'Authentication session hijacking and privilege escalation',
    ],
    suggestedEnvName: (v) => v?.toUpperCase() || 'AUTH_TOKEN',
    remediationInstructions: [
      'Invalidate active sessions / revoke refresh token family in identity provider.',
      'Never hardcode tokens in client or backend source repositories.',
    ],
  },
  {
    id: 'generic-api-key',
    name: 'Generic API Secret Assignment',
    provider: 'Generic Credential',
    pattern: /(?:(?:api_?key|secret_?key|auth_?token|client_?secret|access_?token|private_?key)\s*[:=]\s*["']([A-Za-z0-9_.~-]{20,90})["'])/gi,
    baseConfidence: 80,
    baseRiskWeight: 70,
    minEntropy: 4.1,
    signals: [
      'Sensitive identifier keyword assignment',
      'High Shannon entropy string literal',
    ],
    suggestedEnvName: (v) => (v ? v.toUpperCase() : 'API_KEY'),
    remediationInstructions: [
      'Identify corresponding API provider and rotate credential.',
      'Migrate credential to local .env file (ensure .env is in .gitignore).',
    ],
  },
];
