import { RuleDefinition } from '../types';

export const SECRET_RULES: RuleDefinition[] = [
  {
    id: 'aws-access-key',
    name: 'AWS Access Key ID',
    provider: 'Amazon Web Services',
    // Matches AKIA, ASIA, ABIA, ACCA followed by 16 alphanumeric characters
    pattern: /\b((?:AKIA|ASIA|ABIA|ACCA)[0-9A-Z]{16})\b/g,
    risk: 'CRITICAL',
    baseConfidence: 98,
    signals: ['Known cloud credential prefix', 'Strict 20-char uppercase alphanumeric structure', 'High risk of resource hijacking'],
    remediation: 'Immediately revoke in AWS IAM Console and replace with AWS IAM Roles or environment variables.',
    exampleFix: (v) => `${v || 'AWS_ACCESS_KEY_ID'} = process.env.AWS_ACCESS_KEY_ID`,
  },
  {
    id: 'aws-secret-key',
    name: 'AWS Secret Access Key',
    provider: 'Amazon Web Services',
    // Assignment context with 40-character base64-like string
    pattern: /(?:aws_secret_access_key|aws_secret_key|secret_access_key)\s*[:=]\s*["']([A-Za-z0-9/+=]{40})["']/gi,
    risk: 'CRITICAL',
    minEntropy: 4.2,
    baseConfidence: 92,
    signals: ['Contextual AWS keyword match', '40-character Base64 entropy', 'Pairs with Access Key'],
    remediation: 'Rotate credential immediately in AWS Secrets Manager or IAM.',
    exampleFix: (v) => `${v || 'AWS_SECRET_ACCESS_KEY'} = process.env.AWS_SECRET_ACCESS_KEY`,
  },
  {
    id: 'github-token',
    name: 'GitHub Personal Access Token',
    provider: 'GitHub',
    // ghp_, gho_, ghu_, ghs_, ghr_ or github_pat_
    pattern: /\b(gh[pousr]_[A-Za-z0-9_]{36,255}|github_pat_[A-Za-z0-9_]{82})\b/g,
    risk: 'CRITICAL',
    baseConfidence: 99,
    signals: ['Official GitHub token format prefix', 'Length and character set match', 'Direct repository read/write access'],
    remediation: 'Revoke token at github.com/settings/tokens. Use GitHub Actions secrets or personal environment vars.',
    exampleFix: (v) => `${v || 'GITHUB_TOKEN'} = process.env.GITHUB_TOKEN`,
  },
  {
    id: 'openai-api-key',
    name: 'OpenAI API Key',
    provider: 'OpenAI',
    // sk-proj-... or legacy sk-...
    pattern: /\b(sk-proj-[A-Za-z0-9_-]{48,}|sk-[A-Za-z0-9]{32,48})\b/g,
    risk: 'CRITICAL',
    minEntropy: 4.0,
    baseConfidence: 96,
    signals: ['OpenAI secret key prefix (sk-)', 'High entropy cryptographic key', 'Direct model billing exposure'],
    remediation: 'Revoke key at platform.openai.com/api-keys. Store in .env or cloud secret vault.',
    exampleFix: (v) => `${v || 'OPENAI_API_KEY'} = process.env.OPENAI_API_KEY`,
  },
  {
    id: 'anthropic-api-key',
    name: 'Anthropic Claude API Key',
    provider: 'Anthropic',
    pattern: /\b(sk-ant-[A-Za-z0-9_-]{40,})\b/g,
    risk: 'CRITICAL',
    minEntropy: 3.8,
    baseConfidence: 97,
    signals: ['Anthropic token signature (sk-ant-)', 'High entropy payload'],
    remediation: 'Revoke key in Anthropic Console.',
    exampleFix: (v) => `${v || 'ANTHROPIC_API_KEY'} = process.env.ANTHROPIC_API_KEY`,
  },
  {
    id: 'stripe-secret-key',
    name: 'Stripe Secret Key',
    provider: 'Stripe',
    pattern: /\b((?:sk|rk)_(?:live|test)_[0-9a-zA-Z]{24,34})\b/g,
    risk: 'CRITICAL',
    baseConfidence: 97,
    signals: ['Stripe signature prefix (sk_live/rk_live)', 'High entropy token', 'Direct financial transaction privilege'],
    remediation: 'Roll API key immediately in Stripe Dashboard > Developers > API keys.',
    exampleFix: (v) => `${v || 'STRIPE_SECRET_KEY'} = process.env.STRIPE_SECRET_KEY`,
  },
  {
    id: 'slack-bot-token',
    name: 'Slack Token',
    provider: 'Slack',
    pattern: /\b(xox[baprs]-[0-9A-Za-z-]{10,72})\b/g,
    risk: 'HIGH',
    baseConfidence: 95,
    signals: ['Slack OAuth bot/user prefix (xox*)', 'Workspace communication exposure'],
    remediation: 'Revoke token in api.slack.com/apps.',
    exampleFix: (v) => `${v || 'SLACK_TOKEN'} = process.env.SLACK_BOT_TOKEN`,
  },
  {
    id: 'slack-webhook',
    name: 'Slack Webhook URL',
    provider: 'Slack',
    pattern: /(https:\/\/hooks\.slack\.com\/services\/T[A-Z0-9_]{8,12}\/B[A-Z0-9_]{8,12}\/[A-Za-z0-9_]{24})/g,
    risk: 'HIGH',
    baseConfidence: 98,
    signals: ['Slack Incoming Webhook URL', 'Allows channel spam and impersonation'],
    remediation: 'Delete webhook in Slack App configuration.',
    exampleFix: (v) => `${v || 'SLACK_WEBHOOK_URL'} = process.env.SLACK_WEBHOOK_URL`,
  },
  {
    id: 'private-key',
    name: 'Private Encryption Key',
    provider: 'Cryptography',
    pattern: /(-----BEGIN (?:RSA|EC|DSA|OPENSSH|PGP) PRIVATE KEY-----[\s\S]*?-----END (?:RSA|EC|DSA|OPENSSH|PGP) PRIVATE KEY-----)/g,
    risk: 'CRITICAL',
    baseConfidence: 100,
    signals: ['Standard PEM certificate container', 'Private cryptographic key', 'Complete cryptographic compromise'],
    remediation: 'Immediately regenerate keypair, update authorized_keys or TLS certificates, and do not commit.',
    exampleFix: () => `PRIVATE_KEY = fs.readFileSync(process.env.KEY_PATH, 'utf8')`,
  },
  {
    id: 'database-url',
    name: 'Database Connection String with Credentials',
    provider: 'Database',
    pattern: /\b((?:postgres|postgresql|mysql|mongodb(?:\+srv)?|redis):\/\/[^:\s'"]+:([^@\s'"]+)@[a-zA-Z0-9.-]+(?::[0-9]+)?\/[^\s'"]+)/gi,
    risk: 'HIGH',
    minEntropy: 3.2,
    baseConfidence: 90,
    signals: ['Database URI scheme with embedded user:password', 'Production data exposure risk'],
    remediation: 'Extract credentials to DATABASE_URL environment variable or use IAM authentication.',
    exampleFix: (v) => `${v || 'DATABASE_URL'} = process.env.DATABASE_URL`,
  },
  {
    id: 'jwt-token',
    name: 'JSON Web Token (JWT)',
    provider: 'Identity / Auth',
    pattern: /\b(ey[A-Za-z0-9_-]{15,}\.ey[A-Za-z0-9_-]{15,}\.[A-Za-z0-9_-]{10,})\b/g,
    risk: 'HIGH',
    minEntropy: 4.1,
    baseConfidence: 86,
    signals: ['Base64 header.payload.signature JWT structure', 'Authentication session hijacking risk'],
    remediation: 'Store JWTs in secure cookies or memory; never hardcode tokens in client or server files.',
    exampleFix: (v) => `${v || 'AUTH_TOKEN'} = process.env.AUTH_TOKEN`,
  },
  {
    id: 'generic-api-key',
    name: 'Generic API Key / Secret Assignment',
    provider: 'Generic Credential',
    // Searches for assignments: apiKey = "...", secret_key = "..."
    pattern: /(?:(?:api_?key|secret_?key|auth_?token|client_?secret|access_?token|private_?key)\s*[:=]\s*["']([A-Za-z0-9_.~-]{20,90})["'])/gi,
    risk: 'MEDIUM',
    minEntropy: 4.1,
    baseConfidence: 80,
    signals: ['Sensitive identifier name assignment', 'High entropy string literal'],
    remediation: 'Move confidential credential to .env file.',
    exampleFix: (v) => `${v || 'API_KEY'} = process.env.${(v || 'API_KEY').toUpperCase()}`,
  },
];
